### ISSUE TITLE
minimized legend with condense info

### ISSUE THREAD

**Issue by sahawut** [midas-isg/spewmap#3]
The minimized legend should include:
- [x] Short legend title like Age, Race, Size, Income, etc
- [x] color circles as shown in the full info legend

Note: For race, we should put the first letter into the corresponding circle. For example, an A should be in the circle for Asia.

**Comment by TerenceSperringerJr** [comment]
Title and circles are in mini-legend, but consistency issues remain for 'first letter' labeling and different types of categories.
