### ISSUE TITLE
Point query info

### ISSUE THREAD

**Issue by sahawut** [midas-isg/spewmap#5]
When a user clicks on a household point, it shows data about that household in raw format. 

We should translate code into human readable info. E.g. sexes:[1,2] should translate as sexes:[M,F] or sexes:[Male, Female].

The fields could be grouped. All field that ends with 's' except persons come from people records.

**Comment by TerenceSperringerJr** [comment]
https://github.com/midas-isg/data-format-repository/wiki/SPEW.US-File-Formats

**Comment by TerenceSperringerJr** [comment]
Some translation has been completed, but some could not be due to limited information/lack of details.
